### PR TITLE
Update Style Selector To Use New Atom Convention

### LINKED ISSUE #27: Deprecated selector in `open-plus/styles/open-plus.less`
Autogenerated report for Atom 1.13.0

In `open-plus/styles/open-plus.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .open-plus .region,
atom-text-editor::shadow .open-plus .region` => `atom-text-editor .open-plus .region,
atom-text-editor.editor .open-plus .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

### LINKED ISSUE #29: Deprecation Issue
Atom is displaying a deprecation issue with Open Plus.  Error message says in part "you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--.".

### PR DESCRIPTION
**Pull request by amayer5125**
Replace ::shadow with .editor
Fixes #27, Fixes #29

### CODE REVIEW

**Comment by amayer5125** [comment]
This removes the deprecation warnings from atom

**Comment by amayer5125** [comment]
Is there something else I need to do to get this merged?

**Comment by ChuckPierce** [comment]
@klorenz this is an easy update. Could you merge and release?

**Comment by klorenz** [comment]
done

**Pull request merged**
